// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: checkout.sql

package dal

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, product_id, quantity, total)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, product_id, quantity, total, created_at
`

type CreateOrderParams struct {
	UserID    uuid.UUID      `json:"userId"`
	ProductID uuid.UUID      `json:"productId"`
	Quantity  int32          `json:"quantity"`
	Total     pgtype.Numeric `json:"total"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.ProductID,
		arg.Quantity,
		arg.Total,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}
